(()=>{var M=Object.defineProperty,S=Object.defineProperties;var N=Object.getOwnPropertyDescriptors;var v=Object.getOwnPropertySymbols;var D=Object.prototype.hasOwnProperty,_=Object.prototype.propertyIsEnumerable;var C=(t,e,a)=>e in t?M(t,e,{enumerable:!0,configurable:!0,writable:!0,value:a}):t[e]=a,p=(t,e)=>{for(var a in e||(e={}))D.call(e,a)&&C(t,a,e[a]);if(v)for(var a of v(e))_.call(e,a)&&C(t,a,e[a]);return t},T=(t,e)=>S(t,N(e));var m=(t,e,a)=>new Promise((u,n)=>{var i=r=>{try{o(a.next(r))}catch(l){n(l)}},s=r=>{try{o(a.throw(r))}catch(l){n(l)}},o=r=>r.done?u(r.value):Promise.resolve(r.value).then(i,s);o((a=a.apply(t,e)).next())});function P(t){return t instanceof Date?t.toISOString():Array.isArray(t)?t.map(P):t}function I(t,e){return m(this,null,function*(){var o;let{data:{key:a,params:u}}=t,n,i;try{n=yield e(...u)}catch(r){n=void 0;try{i=r.toString()}catch(l){i="Exception can't be stringified."}}let s={key:a};n!==void 0&&(n=P(n),s.result={type:"string",value:n}),i!==void 0&&(s.error=i),((o=t.source)==null?void 0:o.postMessage).call(o,s,"*")})}function w(t){return typeof window!="undefined"&&window.addEventListener("message",e=>I(e,t.run)),T(p({},t),{json:JSON.stringify(O(t),null,2)})}var R=`
        <svg
          width="48"
          height="48"
          viewBox="0 0 26 27"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M0 14.85L14.3 0V7.29C14.3 11.4653 11.0406 14.85 7.02 14.85H0Z"
            fill="currentColor"
          />
          <path
            d="M11.7 19.71C11.7 15.5347 14.9594 12.15 18.98 12.15H26L11.7 27V19.71Z"
            fill="currentColor"
          />
        </svg>
    `,A=`<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12.0002 34.828L2.58624 25.414C1.80524 24.633 1.80524 23.367 2.58624 22.586L12.0002 13.172L14.8292 16L6.82924 24L14.8292 32L12.0002 34.828Z" fill="currentColor"/>
<path d="M36.0004 34.828L33.1714 32L41.1714 24L33.1714 16L36.0004 13.172L45.4144 22.586C46.1954 23.367 46.1954 24.633 45.4144 25.414L36.0004 34.828Z" fill="currentColor"/>
<path d="M26.5485 5.57617L17.5723 41.4553L21.4527 42.4261L30.4289 6.54697L26.5485 5.57617Z" fill="currentColor"/>
</svg>`;function O(t){let{name:e,description:a,author:u,result:n,params:i,about:s,video:o}=t,{icon:r=A}=t;return r==="glide"&&(r=R),{name:e,description:a,author:u,result:n,about:s,icon:r,video:o,params:Object.entries(i).map(([l,c])=>p({name:l},c))}}var x={timeoutSeconds:10};function b(t){return(new Date().getTime()-t.getTime())/1e3}var y=class{constructor(e=x){this.cache=new Map;this.props=p(p({},e),x)}get(e){return m(this,null,function*(){var n;let{timestamp:a,item:u}=(n=this.cache.get(e))!=null?n:{timestamp:new Date(0)};if(b(a)<this.props.timeoutSeconds)return u;this.cache.delete(e)})}getWith(e,a){return m(this,null,function*(){var i;let{timestamp:u,item:n}=(i=this.cache.get(e))!=null?i:{timestamp:new Date(0)};if(b(u)<this.props.timeoutSeconds)return n;{let s=yield a(e);return this.set(e,s),s}})}set(e,a){return this.cache.set(e,{timestamp:new Date,item:a})}fetch(u){return m(this,arguments,function*(e,a=e){return yield this.getWith(a,()=>fetch(e).then(n=>n.json()))})}};var V=new y,W=w({name:"Mortgage Calculator",description:"Calculates total costs of refinancing based on market assumptions.",author:"Matt Wensing <matt@usesummit.com>",params:{summitApiKey:{displayName:"Summit API Key",type:"string"},loan:{displayName:"Loan Amount",type:"number"},rate:{displayName:"Interest Rate (%)",type:"number"},homePrice:{displayName:"Home Price",type:"number"},homeAppreciation:{displayName:"Home Appreciation Rate (%)",type:"number"},additionalMonthlyPayment:{displayName:"Additional Monthly Payment",type:"number"},years:{displayName:"Loan Term (Years)",type:"number"},propertyTaxRate:{displayName:"Property Tax Rate (%)",type:"number"},propTaxIncreaseRate:{displayName:"Property Tax Increase Rate (%)",type:"number"},taxDiscountRate:{displayName:"Tax Discount Rate (%)",type:"number"}},result:{type:"string"},run(t,e,a,u,n,i,s,o,r,l){return m(this,null,function*(){if(t.value===void 0)return JSON.stringify({args:{summitApiKey:t.value,loan:e.value,rate:a.value,homePrice:u.value,homeAppreciation:n.value,additionalMonthlyPayment:i.value,years:s.value,propertyTaxRate:o.value,propTaxIncreaseRate:r.value,taxDiscountRate:l.value}});let c="https://api.usesummit.com/v1/free-calculators/b79052/the-home-mortgage-calculator/",g=yield V.fetch(c,{method:"POST",headers:{"Content-Type":"application/json","X-Api-Key":t.value},body:JSON.stringify({parameters:{loan:e.value,rate:a.value,home_price:u.value,home_appreciation:n.value,additional_monthly_payment:i.value,years:s.value,property_tax_rate:o.value,prop_tax_increase_rate:r.value,tax_discount_rate:l.value}})}),f=g.results.filter(L=>L.values!==void 0),d=f[f.length-1],h;return d&&d.values?h=Math.round(d.values.total_accrued_interest):h=0,JSON.stringify(g)})}});})();
//# sourceMappingURL=index.js.map
