(()=>{var w=Object.defineProperty,x=Object.defineProperties;var b=Object.getOwnPropertyDescriptors;var d=Object.getOwnPropertySymbols;var L=Object.prototype.hasOwnProperty,M=Object.prototype.propertyIsEnumerable;var g=(t,e,n)=>e in t?w(t,e,{enumerable:!0,configurable:!0,writable:!0,value:n}):t[e]=n,l=(t,e)=>{for(var n in e||(e={}))L.call(e,n)&&g(t,n,e[n]);if(d)for(var n of d(e))M.call(e,n)&&g(t,n,e[n]);return t},f=(t,e)=>x(t,b(e));var u=(t,e,n)=>new Promise((o,a)=>{var s=r=>{try{m(n.next(r))}catch(p){a(p)}},i=r=>{try{m(n.throw(r))}catch(p){a(p)}},m=r=>r.done?o(r.value):Promise.resolve(r.value).then(s,i);m((n=n.apply(t,e)).next())});function h(t){return t instanceof Date?t.toISOString():Array.isArray(t)?t.map(h):t}function S(t,e){return u(this,null,function*(){var m;let{data:{key:n,params:o}}=t,a,s;try{a=yield e(...o)}catch(r){a=void 0;try{s=r.toString()}catch(p){s="Exception can't be stringified."}}let i={key:n};a!==void 0&&(a=h(a),i.result={type:"string",value:a}),s!==void 0&&(i.error=s),((m=t.source)==null?void 0:m.postMessage).call(m,i,"*")})}function C(t){return typeof window!="undefined"&&window.addEventListener("message",e=>S(e,t.run)),f(l({},t),{json:JSON.stringify(_(t),null,2)})}var N=`
        <svg
          width="48"
          height="48"
          viewBox="0 0 26 27"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M0 14.85L14.3 0V7.29C14.3 11.4653 11.0406 14.85 7.02 14.85H0Z"
            fill="currentColor"
          />
          <path
            d="M11.7 19.71C11.7 15.5347 14.9594 12.15 18.98 12.15H26L11.7 27V19.71Z"
            fill="currentColor"
          />
        </svg>
    `,D=`<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12.0002 34.828L2.58624 25.414C1.80524 24.633 1.80524 23.367 2.58624 22.586L12.0002 13.172L14.8292 16L6.82924 24L14.8292 32L12.0002 34.828Z" fill="currentColor"/>
<path d="M36.0004 34.828L33.1714 32L41.1714 24L33.1714 16L36.0004 13.172L45.4144 22.586C46.1954 23.367 46.1954 24.633 45.4144 25.414L36.0004 34.828Z" fill="currentColor"/>
<path d="M26.5485 5.57617L17.5723 41.4553L21.4527 42.4261L30.4289 6.54697L26.5485 5.57617Z" fill="currentColor"/>
</svg>`;function _(t){let{name:e,description:n,author:o,result:a,params:s,about:i,video:m}=t,{icon:r=D}=t;return r==="glide"&&(r=N),{name:e,description:n,author:o,result:a,about:i,icon:r,video:m,params:Object.entries(s).map(([p,c])=>l({name:p},c))}}var v={timeoutSeconds:10};function T(t){return(new Date().getTime()-t.getTime())/1e3}var y=class{constructor(e=v){this.cache=new Map;this.props=l(l({},e),v)}get(e){return u(this,null,function*(){var a;let{timestamp:n,item:o}=(a=this.cache.get(e))!=null?a:{timestamp:new Date(0)};if(T(n)<this.props.timeoutSeconds)return o;this.cache.delete(e)})}getWith(e,n){return u(this,null,function*(){var s;let{timestamp:o,item:a}=(s=this.cache.get(e))!=null?s:{timestamp:new Date(0)};if(T(o)<this.props.timeoutSeconds)return a;{let i=yield n(e);return this.set(e,i),i}})}set(e,n){return this.cache.set(e,{timestamp:new Date,item:n})}fetch(a,s){return u(this,arguments,function*(e,n,o=e){return yield this.getWith(o,()=>fetch(e,n).then(i=>i.json()))})}};var I=new y,Z=C({name:"Mortgage Calculator",description:"Calculates total costs of refinancing based on market assumptions.",author:"Matt Wensing <matt@usesummit.com>",params:{summitApiKey:{displayName:"Summit API Key",type:"string"},loan:{displayName:"Loan Amount",type:"number"},rate:{displayName:"Interest Rate (%)",type:"number"},homePrice:{displayName:"Home Price",type:"number"},homeAppreciation:{displayName:"Home Appreciation Rate (%)",type:"number"},additionalMonthlyPayment:{displayName:"Additional Monthly Payment",type:"number"},years:{displayName:"Loan Term (Years)",type:"number"},propertyTaxRate:{displayName:"Property Tax Rate (%)",type:"number"},propTaxIncreaseRate:{displayName:"Property Tax Increase Rate (%)",type:"number"},taxDiscountRate:{displayName:"Tax Discount Rate (%)",type:"number"}},result:{type:"string"},run(t,e,n,o,a,s,i,m,r,p){return u(this,null,function*(){try{let c=`https://api.usesummit.com/v1/free-calculators/b79052/the-home-mortgage-calculator/?api_key=${t.value}`,P=yield I.fetch(c,{method:"POST",headers:{"Content-Type":"application/json","X-Api-Key":t.value},body:JSON.stringify({options:{start:"2024-04-01",end:"2039-05-01",resolution:"year"},parameters:{loan:e.value,rate:n.value,home_price:o.value,home_appreciation:a.value,additional_monthly_payment:s.value,years:i.value,property_tax_rate:m.value,prop_tax_increase_rate:r.value,tax_discount_rate:p.value}})});return JSON.stringify(P)}catch(c){return JSON.stringify({error:c})}})}});})();
//# sourceMappingURL=index.js.map
