(()=>{var b=Object.defineProperty,L=Object.defineProperties;var M=Object.getOwnPropertyDescriptors;var f=Object.getOwnPropertySymbols;var S=Object.prototype.hasOwnProperty,N=Object.prototype.propertyIsEnumerable;var h=(t,e,n)=>e in t?b(t,e,{enumerable:!0,configurable:!0,writable:!0,value:n}):t[e]=n,c=(t,e)=>{for(var n in e||(e={}))S.call(e,n)&&h(t,n,e[n]);if(f)for(var n of f(e))N.call(e,n)&&h(t,n,e[n]);return t},C=(t,e)=>L(t,M(e));var u=(t,e,n)=>new Promise((s,a)=>{var o=r=>{try{m(n.next(r))}catch(l){a(l)}},i=r=>{try{m(n.throw(r))}catch(l){a(l)}},m=r=>r.done?s(r.value):Promise.resolve(r.value).then(o,i);m((n=n.apply(t,e)).next())});function v(t){return t instanceof Date?t.toISOString():Array.isArray(t)?t.map(v):t}function D(t,e){return u(this,null,function*(){var m;let{data:{key:n,params:s}}=t,a,o;try{a=yield e(...s)}catch(r){a=void 0;try{o=r.toString()}catch(l){o="Exception can't be stringified."}}let i={key:n};a!==void 0&&(a=v(a),i.result={type:"string",value:a}),o!==void 0&&(i.error=o),((m=t.source)==null?void 0:m.postMessage).call(m,i,"*")})}function T(t){return typeof window!="undefined"&&window.addEventListener("message",e=>D(e,t.run)),C(c({},t),{json:JSON.stringify(I(t),null,2)})}var _=`
        <svg
          width="48"
          height="48"
          viewBox="0 0 26 27"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M0 14.85L14.3 0V7.29C14.3 11.4653 11.0406 14.85 7.02 14.85H0Z"
            fill="currentColor"
          />
          <path
            d="M11.7 19.71C11.7 15.5347 14.9594 12.15 18.98 12.15H26L11.7 27V19.71Z"
            fill="currentColor"
          />
        </svg>
    `,R=`<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12.0002 34.828L2.58624 25.414C1.80524 24.633 1.80524 23.367 2.58624 22.586L12.0002 13.172L14.8292 16L6.82924 24L14.8292 32L12.0002 34.828Z" fill="currentColor"/>
<path d="M36.0004 34.828L33.1714 32L41.1714 24L33.1714 16L36.0004 13.172L45.4144 22.586C46.1954 23.367 46.1954 24.633 45.4144 25.414L36.0004 34.828Z" fill="currentColor"/>
<path d="M26.5485 5.57617L17.5723 41.4553L21.4527 42.4261L30.4289 6.54697L26.5485 5.57617Z" fill="currentColor"/>
</svg>`;function I(t){let{name:e,description:n,author:s,result:a,params:o,about:i,video:m}=t,{icon:r=R}=t;return r==="glide"&&(r=_),{name:e,description:n,author:s,result:a,about:i,icon:r,video:m,params:Object.entries(o).map(([l,y])=>c({name:l},y))}}var P={timeoutSeconds:10};function w(t){return(new Date().getTime()-t.getTime())/1e3}var d=class{constructor(e=P){this.cache=new Map;this.props=c(c({},e),P)}get(e){return u(this,null,function*(){var a;let{timestamp:n,item:s}=(a=this.cache.get(e))!=null?a:{timestamp:new Date(0)};if(w(n)<this.props.timeoutSeconds)return s;this.cache.delete(e)})}getWith(e,n){return u(this,null,function*(){var o;let{timestamp:s,item:a}=(o=this.cache.get(e))!=null?o:{timestamp:new Date(0)};if(w(s)<this.props.timeoutSeconds)return a;{let i=yield n(e);return this.set(e,i),i}})}set(e,n){return this.cache.set(e,{timestamp:new Date,item:n})}fetch(a,o){return u(this,arguments,function*(e,n,s=e){return yield this.getWith(s,()=>fetch(e,n).then(i=>i.json()))})}};var O=new d,J=T({name:"Mortgage Calculator",description:"Calculates total costs of refinancing based on market assumptions.",author:"Matt Wensing <matt@usesummit.com>",params:{summitApiKey:{displayName:"Summit API Key",type:"string"},loan:{displayName:"Loan Amount",type:"number"},rate:{displayName:"Interest Rate (%)",type:"number"},homePrice:{displayName:"Home Price",type:"number"},homeAppreciation:{displayName:"Home Appreciation Rate (%)",type:"number"},additionalMonthlyPayment:{displayName:"Additional Monthly Payment",type:"number"},years:{displayName:"Loan Term (Years)",type:"number"},propertyTaxRate:{displayName:"Property Tax Rate (%)",type:"number"},propTaxIncreaseRate:{displayName:"Property Tax Increase Rate (%)",type:"number"},taxDiscountRate:{displayName:"Tax Discount Rate (%)",type:"number"}},result:{type:"string"},run(t,e,n,s,a,o,i,m,r,l){return u(this,null,function*(){let y;try{let p=`https://api.usesummit.com/v1/free-calculators/b79052/the-home-mortgage-calculator/?api_key=${t.value}`;y=yield O.fetch(p,{method:"POST",headers:{"Content-Type":"application/json","X-Api-Key":t.value},body:JSON.stringify({options:{start:"2024-04-01",end:"2054-05-01",resolution:"year"},parameters:{loan:e.value,rate:n.value,home_price:s.value,home_appreciation:a.value,additional_monthly_payment:o.value,years:i.value,property_tax_rate:m.value,prop_tax_increase_rate:r.value,tax_discount_rate:l.value}})})}catch(p){return JSON.stringify({error:p})}let g=y.results.filter(p=>p.values&&Object.entries(p.values).length>0),x=g[g.length-1];return JSON.stringify({mortgageData:x})})}});})();
//# sourceMappingURL=index.js.map
